### ISSUE TITLE
Unable to sign transactions on TESTNET 

### ISSUE THREAD

**Issue by guudc** [stellar/freighter#1001]
When i tried signing a transaction on the testnet with freighter API. I always get a scvalType member error.

Not until i activated experimental feature on the Wallet before it worked properly

**Comment by aristidesstaffieri** [comment]
thanks for reporting @guudc, I've identified the issue and will be getting review/publishing patch asap. I'll post back here as we have updates.

**Comment by aristidesstaffieri** [comment]
I've opened this PR which fixes the issue. 
https://github.com/stellar/freighter/pull/1002

We're working to get this reviewed and included in the upcoming release, this will likely take us into next week due to the store approval lifecycle. I will update here once we are pubished.

**Comment by piyalbasu** [comment]
This was released in version 5.6.4 and is live in extension stores now. [Release notes](https://github.com/stellar/freighter/releases/tag/5.6.4)

**Comment by guudc** [comment]
I am a software developer too. I would be glad to help
