### ISSUE TITLE
Currently selected network affects network settings fields

### ISSUE THREAD

**Issue by aristidesstaffieri** [stellar/freighter#1034]
### What version are you using?
5.8.0

### What did you do?
Select Mainnet as your active network, then go into network settings and click on Testnet and you can see that the field for the Soroban RPC is not present when it should be.

### What did you expect to see?
A field for the Soroban RPC URL.

### What did you see instead?
Missing field.

**Comment by japuiglaucia** [comment]
Currently selected network affects network settings fields #1034

**Comment by piyalbasu** [comment]
Closing as we agreed to remove this from the UI
