### ISSUE TITLE
Insecure connection error when using `signBlob` function

### ISSUE THREAD

**Issue by miguelnietoa** [stellar/freighter#1073]
### What version are you using?

- Freighter extension: `5.12.0`
- `@stellar/freighter-api`: `1.7.1`

### What did you do?

I've found that the Freighter wallet when the Experimental mode is disabled, shows up this message but the website does have SSL certificate.
It happens even in the Freighter docs website https://docs.freighter.app/docs/playground/signBlob
![image](https://github.com/stellar/freighter/assets/39246879/c1075afb-b635-4bd4-9b82-ca2585dd1812)

I have noticed that this happens only when using the `signBlob` function.

### What did you expect to see?
The UI to sign the blob.

### What did you see instead?
An insecure connection error as shown in the image above.

**Comment by aristidesstaffieri** [comment]
Thanks for reporting @miguelnietoa. I've opened this PR to resolve the faulty check.
https://github.com/stellar/freighter/pull/1074

**Comment by piyalbasu** [comment]
@miguelnietoa This is now live in release 5.12.1: https://github.com/stellar/freighter/releases/tag/5.12.1
