### ISSUE TITLE
Duplicate words in seed phrase cannot be confirmed

### ISSUE THREAD

**Issue by aristidesstaffieri** [stellar/freighter#1113]
### What version are you using?
5.15.2

### What did you do?
Initialized a key and drew a seed phrase with duplicate words, in this situation you have to guess which one of the duplicates to click first.

### What did you expect to see?
A more clear way to deal with duplicate words in seed phrases

### What did you see instead?
Have to guess which instance of the repeated word comes first

Thread - https://discord.com/channels/897514728459468821/1019346446014759013/1207383358917840956

**Comment by Blake-Emigro** [comment]
I'm the one who had the experience and brought this up in Discord. Actually, I didn't even have the exact experience as described above as I got lucky and chose the correct word order of the duplicates, once I discovered that there were two instances of the same word to chose from for the confirmation step.

My main point was that having the possibility for duplicate recovery words is an unexpected issue for the new user to experience and potentially slows the sign-up process, making for a bad UX, in addition to this actual UI bug.

**Comment by aristidesstaffieri** [comment]
I revisited the implementation and original report, here are the details - 

You can produce a seed phrase with more than 1 instance of the same word.
If you draw a seed like this, during the confirmation phase, you will be shown 1 selector("clickable word bubble") per instance of the word. 

In our implementation of the phrase confirmation, we use a composite key of the `{seed word}-{index in seed}` to track the words in the seed. Because of this, when a user has duplicate words in their seed phrase, they have to guess at the index of the word during confirmation.

There are two things wrong with this flow related to duplicate words in seed - 
1. Duplicate words should be interchangeable at confirmation time, I see no reason to use the index to build the composite key. We should be able to use only the word string and make duplicate words interchangeable during confirmation.
2. Duplicate words confuse users. In [the original report](https://discord.com/channels/761985725453303838/761985725453303841/1207381379462209546), the user did not notice that there were duplicate confirmation actions and was confused about how to confirm the second instance of the word.

Possible action items - 
Refactor seed phrase confirmation to not use index based keys per word.
Refactor seed phrase confirmation to discard phrases with duplicate words.
REdesign seed phrase confirmation in order to make duplicate words less confusing.
