### ISSUE TITLE
"contractFn not set" error when trying to sign and execute a transaction

### ISSUE THREAD

**Issue by findolor** [stellar/freighter#1130]
### What version are you using?

`"@stellar/freighter-api": "^1.6.0"`
`"stellar-sdk": "^11.1.0"`

### What did you do?

I have created a transaction with this XDR value:

```
AAAAAgAAAABcC06JbJHaqJtgzY3paS/1twoc1fC2ptcZxJVHMi129QF4CowAACJDAAAABAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAGAAAAAAAAAABdWYyRveRv3hO9vfad9RxDbdTv8KbBAlR4uNaRNxffXcAAAAGZGVwbG95AAAAAAAFAAAAEgAAAAAAAAAAXAtOiWyR2qibYM2N6Wkv9bcKHNXwtqbXGcSVRzItdvUAAAANAAAAILYm0ODRjngzRheM6LhBu9iwpJpeADBg85g4YVmG6sfhAAAADQAAACCDADAblkQfOFwkAsjIYpJiAlvOg04TpZnjMpVEOd4FggAAAA8AAAAEaW5pdAAAABAAAAABAAAAAwAAABIAAAAAAAAAAFwLTolskdqom2DNjelpL/W3ChzV8Lam1xnElUcyLXb1AAAAEAAAAAEAAAACAAAAEQAAAAEAAAACAAAADwAAAAVzaGFyZQAAAAAAAAoAAAAAAAAAAAAAAAAAAB9AAAAADwAAAAtzaGFyZWhvbGRlcgAAAAASAAAAAAAAAABcC06JbJHaqJtgzY3paS/1twoc1fC2ptcZxJVHMi129QAAABEAAAABAAAAAgAAAA8AAAAFc2hhcmUAAAAAAAAKAAAAAAAAAAAAAAAAAAAH0AAAAA8AAAALc2hhcmVob2xkZXIAAAAAEgAAAAAAAAAAMSzBHMZn1IDcy+vOybOLF/45hUA6k6NS4+Cg6AtT3kkAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAF1ZjJG95G/eE7299p31HENt1O/wpsECVHi41pE3F99dwAAAAZkZXBsb3kAAAAAAAUAAAASAAAAAAAAAABcC06JbJHaqJtgzY3paS/1twoc1fC2ptcZxJVHMi129QAAAA0AAAAgtibQ4NGOeDNGF4zouEG72LCkml4AMGDzmDhhWYbqx+EAAAANAAAAIIMAMBuWRB84XCQCyMhikmICW86DThOlmeMylUQ53gWCAAAADwAAAARpbml0AAAAEAAAAAEAAAADAAAAEgAAAAAAAAAAXAtOiWyR2qibYM2N6Wkv9bcKHNXwtqbXGcSVRzItdvUAAAAQAAAAAQAAAAIAAAARAAAAAQAAAAIAAAAPAAAABXNoYXJlAAAAAAAACgAAAAAAAAAAAAAAAAAAH0AAAAAPAAAAC3NoYXJlaG9sZGVyAAAAABIAAAAAAAAAAFwLTolskdqom2DNjelpL/W3ChzV8Lam1xnElUcyLXb1AAAAEQAAAAEAAAACAAAADwAAAAVzaGFyZQAAAAAAAAoAAAAAAAAAAAAAAAAAAAfQAAAADwAAAAtzaGFyZWhvbGRlcgAAAAASAAAAAAAAAAAxLMEcxmfUgNzL687Js4sX/jmFQDqTo1Lj4KDoC1PeSQAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAABcC06JbJHaqJtgzY3paS/1twoc1fC2ptcZxJVHMi129YMAMBuWRB84XCQCyMhikmICW86DThOlmeMylUQ53gWCAAAAALYm0ODRjngzRheM6LhBu9iwpJpeADBg85g4YVmG6sfhAAAAAAAAAAEAAAAAAAAAAwAAAAYAAAABdWYyRveRv3hO9vfad9RxDbdTv8KbBAlR4uNaRNxffXcAAAAUAAAAAQAAAAcOwWGqJhSNc1oCn2EZBDGXKvafZvoA5Sj57GL042BQnAAAAAe2JtDg0Y54M0YXjOi4QbvYsKSaXgAwYPOYOGFZhurH4QAAAAQAAAAGAAAAAdEkRa58va4hsKNZSwjj+nJAQ5bNKUMEt8yWvJ4/A1fYAAAAEAAAAAEAAAACAAAADwAAAAVTaGFyZQAAAAAAABIAAAAAAAAAADEswRzGZ9SA3Mvrzsmzixf+OYVAOpOjUuPgoOgLU95JAAAAAQAAAAYAAAAB0SRFrny9riGwo1lLCOP6ckBDls0pQwS3zJa8nj8DV9gAAAAQAAAAAQAAAAIAAAAPAAAABVNoYXJlAAAAAAAAEgAAAAAAAAAAXAtOiWyR2qibYM2N6Wkv9bcKHNXwtqbXGcSVRzItdvUAAAABAAAABgAAAAHRJEWufL2uIbCjWUsI4/pyQEOWzSlDBLfMlryePwNX2AAAABAAAAABAAAAAQAAAA8AAAAMU2hhcmVob2xkZXJzAAAAAQAAAAYAAAAB0SRFrny9riGwo1lLCOP6ckBDls0pQwS3zJa8nj8DV9gAAAAUAAAAAQCKFZEAADK8AAADhAAAAAABaMhMAAAAAA==
```

[Laboratory link for the XDR](https://laboratory.stellar.org/#xdr-viewer?input=AAAAAgAAAABcC06JbJHaqJtgzY3paS%2F1twoc1fC2ptcZxJVHMi129QF4CowAACJDAAAABAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAGAAAAAAAAAABdWYyRveRv3hO9vfad9RxDbdTv8KbBAlR4uNaRNxffXcAAAAGZGVwbG95AAAAAAAFAAAAEgAAAAAAAAAAXAtOiWyR2qibYM2N6Wkv9bcKHNXwtqbXGcSVRzItdvUAAAANAAAAILYm0ODRjngzRheM6LhBu9iwpJpeADBg85g4YVmG6sfhAAAADQAAACCDADAblkQfOFwkAsjIYpJiAlvOg04TpZnjMpVEOd4FggAAAA8AAAAEaW5pdAAAABAAAAABAAAAAwAAABIAAAAAAAAAAFwLTolskdqom2DNjelpL%2FW3ChzV8Lam1xnElUcyLXb1AAAAEAAAAAEAAAACAAAAEQAAAAEAAAACAAAADwAAAAVzaGFyZQAAAAAAAAoAAAAAAAAAAAAAAAAAAB9AAAAADwAAAAtzaGFyZWhvbGRlcgAAAAASAAAAAAAAAABcC06JbJHaqJtgzY3paS%2F1twoc1fC2ptcZxJVHMi129QAAABEAAAABAAAAAgAAAA8AAAAFc2hhcmUAAAAAAAAKAAAAAAAAAAAAAAAAAAAH0AAAAA8AAAALc2hhcmVob2xkZXIAAAAAEgAAAAAAAAAAMSzBHMZn1IDcy%2BvOybOLF%2F45hUA6k6NS4%2BCg6AtT3kkAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAF1ZjJG95G%2FeE7299p31HENt1O%2FwpsECVHi41pE3F99dwAAAAZkZXBsb3kAAAAAAAUAAAASAAAAAAAAAABcC06JbJHaqJtgzY3paS%2F1twoc1fC2ptcZxJVHMi129QAAAA0AAAAgtibQ4NGOeDNGF4zouEG72LCkml4AMGDzmDhhWYbqx%2BEAAAANAAAAIIMAMBuWRB84XCQCyMhikmICW86DThOlmeMylUQ53gWCAAAADwAAAARpbml0AAAAEAAAAAEAAAADAAAAEgAAAAAAAAAAXAtOiWyR2qibYM2N6Wkv9bcKHNXwtqbXGcSVRzItdvUAAAAQAAAAAQAAAAIAAAARAAAAAQAAAAIAAAAPAAAABXNoYXJlAAAAAAAACgAAAAAAAAAAAAAAAAAAH0AAAAAPAAAAC3NoYXJlaG9sZGVyAAAAABIAAAAAAAAAAFwLTolskdqom2DNjelpL%2FW3ChzV8Lam1xnElUcyLXb1AAAAEQAAAAEAAAACAAAADwAAAAVzaGFyZQAAAAAAAAoAAAAAAAAAAAAAAAAAAAfQAAAADwAAAAtzaGFyZWhvbGRlcgAAAAASAAAAAAAAAAAxLMEcxmfUgNzL687Js4sX%2FjmFQDqTo1Lj4KDoC1PeSQAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAABcC06JbJHaqJtgzY3paS%2F1twoc1fC2ptcZxJVHMi129YMAMBuWRB84XCQCyMhikmICW86DThOlmeMylUQ53gWCAAAAALYm0ODRjngzRheM6LhBu9iwpJpeADBg85g4YVmG6sfhAAAAAAAAAAEAAAAAAAAAAwAAAAYAAAABdWYyRveRv3hO9vfad9RxDbdTv8KbBAlR4uNaRNxffXcAAAAUAAAAAQAAAAcOwWGqJhSNc1oCn2EZBDGXKvafZvoA5Sj57GL042BQnAAAAAe2JtDg0Y54M0YXjOi4QbvYsKSaXgAwYPOYOGFZhurH4QAAAAQAAAAGAAAAAdEkRa58va4hsKNZSwjj%2BnJAQ5bNKUMEt8yWvJ4%2FA1fYAAAAEAAAAAEAAAACAAAADwAAAAVTaGFyZQAAAAAAABIAAAAAAAAAADEswRzGZ9SA3Mvrzsmzixf%2BOYVAOpOjUuPgoOgLU95JAAAAAQAAAAYAAAAB0SRFrny9riGwo1lLCOP6ckBDls0pQwS3zJa8nj8DV9gAAAAQAAAAAQAAAAIAAAAPAAAABVNoYXJlAAAAAAAAEgAAAAAAAAAAXAtOiWyR2qibYM2N6Wkv9bcKHNXwtqbXGcSVRzItdvUAAAABAAAABgAAAAHRJEWufL2uIbCjWUsI4%2FpyQEOWzSlDBLfMlryePwNX2AAAABAAAAABAAAAAQAAAA8AAAAMU2hhcmVob2xkZXJzAAAAAQAAAAYAAAAB0SRFrny9riGwo1lLCOP6ckBDls0pQwS3zJa8nj8DV9gAAAAUAAAAAQCKFZEAADK8AAADhAAAAAABaMhMAAAAAA%3D%3D&type=TransactionEnvelope&network=test)

Clicked on review button in Freighter popup to sign and execute the transaction.

### What did you expect to see?

In the previous version of Freighter (the one that didn't show the inputs and more information about the transaction), I had no problems signing and broadcasting transactions. I am expecting the same result from the new version of the wallet.

The inputs are showing correctly, I can see what I have included in the transaction and the method I am calling so there is no problem there.

<img width="1584" alt="Screenshot 2024-02-21 at 10 07 57" src="https://github.com/stellar/freighter/assets/16416963/302e0756-a7ac-440b-82af-e089d6b637fb">

<img width="1584" alt="Screenshot 2024-02-21 at 10 08 03" src="https://github.com/stellar/freighter/assets/16416963/60a7258e-4ccf-4c0f-b55a-44fdcbc9f903">

<img width="1584" alt="Screenshot 2024-02-21 at 10 08 08" src="https://github.com/stellar/freighter/assets/16416963/ab4addc9-4f5d-4321-b5e8-bd938e4ccda7">

### What did you see instead?

I get a blank screen in the popup. Whenever I check the console to check for any errors I see this one:

```
83.min.js:2 TypeError: contractFn not set
    at n.get (397.min.js:2:446101)
    at n.<computed> [as contractFn] (397.min.js:2:447488)
    at Bc (index.min.js:1:271485)
    at Array.map (<anonymous>)
    at Lc (index.min.js:1:271725)
    at aa (83.min.js:2:628702)
    at Ws (83.min.js:2:680795)
    at ju (83.min.js:2:668074)
    at ku (83.min.js:2:668002)
    at Ou (83.min.js:2:667865)
    at yu (83.min.js:2:664852)
    at 83.min.js:2:614624
    at t.unstable_runWithPriority (83.min.js:2:691692)
    at Wo (83.min.js:2:614401)
    at Xo (83.min.js:2:614569)
    at Go (83.min.js:2:614504)
    at pu (83.min.js:2:662237)
    at Object.enqueueSetState (83.min.js:2:618478)
    at g.setState (83.min.js:2:716502)
    at 83.min.js:2:5038
    at n (83.min.js:2:414694)
    at 83.min.js:2:414924
    at Array.forEach (<anonymous>)
    at Object.notifyListeners (83.min.js:2:414894)
    at j (83.min.js:2:418396)
    at 83.min.js:2:418715
    at Object.confirmTransitionTo (83.min.js:2:414633)
    at 83.min.js:2:418670
    at I (83.min.js:2:418882)
```

<img width="1584" alt="Screenshot 2024-02-21 at 10 10 05" src="https://github.com/stellar/freighter/assets/16416963/7c372e25-7f41-400e-b2f4-adb8d2dabc2f">

**Comment by findolor** [comment]
@aristidesstaffieri Happy to help you guys and thanks for letting me know about the new release!

**Comment by aristidesstaffieri** [comment]
@findolor 5.17.0 was just published and is available, please let me know if you continue to see issues related to this. 
https://github.com/stellar/freighter/releases/tag/5.17.0

**Comment by findolor** [comment]
@aristidesstaffieri Just tried it and everything works perfectly on my side. Thanks for fixing the issue!
