### ISSUE TITLE
Add two more tokenlists to Freighter

### ISSUE THREAD

**Issue by namankumar** [stellar/freighter#1174]
### What problem does your feature solve?
Freighter has implemented the Tokenlist standard, and has integrated with the only available tokenlist at the time, 
 [stellar.expert token list](https://stellar.expert/asset-lists). This request is to add two more tokenlists, thus giving user the choice of tokenlists and removing reliance on one curator.

An idea is for Freighter to co-relate security of an asset with the number of tokenlists it's on. So if an asset is on both stellar.expert and soroswap tokenlists, it's more trusted vs. if it was only on one list. 

### What would you like to see?
- Add a second tokenlist, which was released by Soroswap today
` https://raw.githubusercontent.com/soroswap/token-list/main/tokenList.json`
- Add a third tokenlist, which was released by Lobstr today
`https://lobstr.co/api/v1/sep/assets/curated.json`

### What alternatives are there?
N/A

**Comment by namankumar** [comment]
Updated main ticket with link to Lobstr's tokenlist as well.

**Comment by piyalbasu** [comment]
Released in version https://github.com/stellar/freighter/releases/tag/5.18.0
