### ISSUE TITLE
Standalone SAC transfers fail

### ISSUE THREAD

**Issue by Ryang-21** [stellar/freighter#1201]
### What version are you using?
15.17.4

### What did you do?
Attempting to sign a stellar token transfer on a standalone network results in type error "Cannot read properties of undefined (reading 'symbol')"

### What did you expect to see?
The screen that displays what tokens are being transferred

### What did you see instead?
A screen with Unexpected Error on it

**Comment by piyalbasu** [comment]
@Ryang-21 Thanks for raising this issue. Would you be comfortable sharing the XDR you're trying to sign? I can look into this right away

**Comment by Ryang-21** [comment]
Yeah this is the xdr ```AAAAAgAAAACmM8CaFtRAuN8AfW/mzHnO/OhiriiKjNyWbxzTvWmN8gAEfw0AAADUAAAABgAAAAEAAAAAAAAAAAAAAABl/tVvAAAAAAAAAAEAAAAAAAAAGAAAAAAAAAAB0jTbaXZlNO0JWRX+ybfaRL6qmmRHGBij+IuDmCqn9fAAAAAGc3VibWl0AAAAAAAEAAAAEgAAAAAAAAAApjPAmhbUQLjfAH1v5sx5zvzoYq4oiozclm8c071pjfIAAAASAAAAAAAAAACmM8CaFtRAuN8AfW/mzHnO/OhiriiKjNyWbxzTvWmN8gAAABIAAAAAAAAAAKYzwJoW1EC43wB9b+bMec786GKuKIqM3JZvHNO9aY3yAAAAEAAAAAEAAAABAAAAEQAAAAEAAAADAAAADwAAAAdhZGRyZXNzAAAAABIAAAAB2LKxTGD+y2X7KqgcvqedCDXK/A4NhR+GESV8HltB4cIAAAAPAAAABmFtb3VudAAAAAAACgAAAAAAAAAAAAAAAAX14QAAAAAPAAAADHJlcXVlc3RfdHlwZQAAAAMAAAACAAAAAQAAAAAAAAAAAAAAAdI022l2ZTTtCVkV/sm32kS+qppkRxgYo/iLg5gqp/XwAAAABnN1Ym1pdAAAAAAABAAAABIAAAAAAAAAAKYzwJoW1EC43wB9b+bMec786GKuKIqM3JZvHNO9aY3yAAAAEgAAAAAAAAAApjPAmhbUQLjfAH1v5sx5zvzoYq4oiozclm8c071pjfIAAAASAAAAAAAAAACmM8CaFtRAuN8AfW/mzHnO/OhiriiKjNyWbxzTvWmN8gAAABAAAAABAAAAAQAAABEAAAABAAAAAwAAAA8AAAAHYWRkcmVzcwAAAAASAAAAAdiysUxg/stl+yqoHL6nnQg1yvwODYUfhhElfB5bQeHCAAAADwAAAAZhbW91bnQAAAAAAAoAAAAAAAAAAAAAAAAF9eEAAAAADwAAAAxyZXF1ZXN0X3R5cGUAAAADAAAAAgAAAAEAAAAAAAAAAdiysUxg/stl+yqoHL6nnQg1yvwODYUfhhElfB5bQeHCAAAACHRyYW5zZmVyAAAAAwAAABIAAAAAAAAAAKYzwJoW1EC43wB9b+bMec786GKuKIqM3JZvHNO9aY3yAAAAEgAAAAHSNNtpdmU07QlZFf7Jt9pEvqqaZEcYGKP4i4OYKqf18AAAAAoAAAAAAAAAAAAAAAAF9eEAAAAAAAAAAAEAAAAAAAAABQAAAAYAAAAB0jTbaXZlNO0JWRX+ybfaRL6qmmRHGBij+IuDmCqn9fAAAAAQAAAAAQAAAAIAAAAPAAAACkVtaXNDb25maWcAAAAAAAMAAAABAAAAAQAAAAYAAAAB0jTbaXZlNO0JWRX+ybfaRL6qmmRHGBij+IuDmCqn9fAAAAAQAAAAAQAAAAIAAAAPAAAACVJlc0NvbmZpZwAAAAAAABIAAAAB2LKxTGD+y2X7KqgcvqedCDXK/A4NhR+GESV8HltB4cIAAAABAAAABgAAAAHSNNtpdmU07QlZFf7Jt9pEvqqaZEcYGKP4i4OYKqf18AAAABQAAAABAAAABgAAAAHYsrFMYP7LZfsqqBy+p50INcr8Dg2FH4YRJXweW0HhwgAAABQAAAABAAAABx60bfnfNxPUhLG2uv7J2MonbPTwLWRC1QXBTpgXWz1QAAAABAAAAAAAAAAApjPAmhbUQLjfAH1v5sx5zvzoYq4oiozclm8c071pjfIAAAAGAAAAAdI022l2ZTTtCVkV/sm32kS+qppkRxgYo/iLg5gqp/XwAAAAEAAAAAEAAAACAAAADwAAAAlQb3NpdGlvbnMAAAAAAAASAAAAAAAAAACmM8CaFtRAuN8AfW/mzHnO/OhiriiKjNyWbxzTvWmN8gAAAAEAAAAGAAAAAdI022l2ZTTtCVkV/sm32kS+qppkRxgYo/iLg5gqp/XwAAAAEAAAAAEAAAACAAAADwAAAAdSZXNEYXRhAAAAABIAAAAB2LKxTGD+y2X7KqgcvqedCDXK/A4NhR+GESV8HltB4cIAAAABAAAABgAAAAHYsrFMYP7LZfsqqBy+p50INcr8Dg2FH4YRJXweW0HhwgAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAdI022l2ZTTtCVkV/sm32kS+qppkRxgYo/iLg5gqp/XwAAAAAQFiGMwAAMu8AAAEAAAAAAAABH6pAAAAAA==```

**Comment by piyalbasu** [comment]
@Ryang-21 This is now live in release 5.17.5: https://github.com/stellar/freighter/releases/tag/5.17.5

Upgrading should fix your issue. Thanks for your patience!
