### ISSUE TITLE
Ledger wallet: add hash signing capabilities 

### ISSUE THREAD

**Issue by tomerweller** [stellar/freighter#1258]
Freighter currently uses the "Sign Transaction" method to sign transactions using Ledger hardware wallet. This decodes the transaction and presents its details on Ledger's screen. However, this does not work in all cases:
1. Unsupported protocol version. For example signing Soroban invocations (P20) doesn't currently work on the released Ledger app (P19). This is a recurring theme, it takes time to release ledger apps. 
2. Complex data types like Arrays or Maps 
3. Large transactions (More than 1120 bytes on Nano S and more than 5120 bytes on Nano SP and X)  

Alternatively, we could use the "Sign Hash" method to bypass these limitations. However, this is a less secure option so should be gated behind an optional flag with an appropriate warning. The user will have to compare the hash on screen with the transaction hash.

**Comment by tomerweller** [comment]
https://github.com/stellar/laboratory/issues/833

**Comment by piyalbasu** [comment]
Released in [5.20.0](https://github.com/stellar/freighter/releases/tag/5.20.0)
