### ISSUE TITLE
Unable to login with passphrase to Freighter from Albedo 

### ISSUE THREAD

**Issue by katovBash** [stellar/freighter#1364]
I'm trying to login to Freighter with account of Albedo. 
I have successful login, but I have seen my assets. 

We have thread and solution, but anyway it looks strange. 
https://discord.com/channels/897514728459468821/1259032360033189920

**Comment by GTHubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)
Thank you for posting @katovBash
