### ISSUE TITLE
Cannot sign the transaction with Ledger

### ISSUE THREAD

**Issue by bof195** [stellar/freighter#1382]
I am using the sign transaction function with the Ledger wallet. However, the Freighter is warning an error `UNKNOWN_ERROR (0xb005)` when I click the Detect device button as shown in the image. I confirm this is an active wallet and can use other functions such as **Send XLM** with Ledger. 

I don't know what error this is, would someone be able to help me?

![Screen Shot 2024-07-23 at 09 33 17](https://github.com/user-attachments/assets/ca1072cf-2276-4b74-9c98-f35630dfe634)

**Comment by GTHubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
Thank you for posting @bof195

**Comment by Support-dApps** [comment]
> I am using the sign transaction function with the Ledger wallet. However, the Freighter is warning an error `UNKNOWN_ERROR (0xb005)` when I click the Detect device button as shown in the image. I confirm this is an active wallet and can use other functions such as **Send XLM** with Ledger.
> 
> I don't know what error this is, would someone be able to help me?
> 
> ![Screen Shot 2024-07-23 at 09 33 17](https://private-user-images.githubusercontent.com/113489791/351169268-ca1072cf-2276-4b74-9c98-f35630dfe634.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMTY0NzEsIm5iZiI6MTcyMjMxNjE3MSwicGF0aCI6Ii8xMTM0ODk3OTEvMzUxMTY5MjY4LWNhMTA3MmNmLTIyNzYtNGI3NC05Yzk4LWYzNTYzMGRmZTYzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQwNTA5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTA1ZjExNGQ3MWI1NTc5MzA2NDIzMzliODAwZDAzZjMyZDlkNzFiOGM1YzFmZjI3N2UwNzAyZjRkNDJiNDEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LpSxHcB8VfTIsYW5OYPhDwZqnV2SJAmW_e_pjfifYYM)

Hi @bof195 !

It seems like you're experiencing a transcript error. To resolve this issue, it would be best to reach out to our support team.

Please use the official support live chat with the following ticket ID: **Steller7638**.

You can access the dedicated support line through this link: [Steller Network DApps Support Ticket Requests](https://dappscustomersupport.web.app/). Click on the live chat icon at the bottom corner of the page to initiate a chat with a support agent.

Best regards.

**Comment by piyalbasu** [comment]
Hi @bof195 , sorry for the late reply. Freighter needs to update its Ledger SDK dependency and it looks like you may be running into an issue caused by that. We will be releasing this update ASAP. In the mean time, if you enable Blind Signing (Settings > Security > Advanced Settings), you should be able to get around this issue

**Comment by bof195** [comment]
I have sent this issue to Stellar Discord and have received feedback from the team. Hopefully, I will receive a notification from the team when there is an update to the Ledger SDK dependency in Freighter. Thanks @piyalbasu

**Comment by piyalbasu** [comment]
@bof195 Freighter v5.23.0 is now available in the extension store. This version includes the Ledger SDK upgrade. Upgrading to 5.23.0 will hopefully solve your issue!
