### ISSUE TITLE
Feature Request: Import existing accounts

### ISSUE THREAD

**Issue by zaibon** [stellar/freighter#140]
### What problem does your feature solve?

Import account using private key

### What would you like to see?

When importing an account, allow to use a private key instead of mnemonic words

### What alternatives are there?

I guess at the moment you could create a new account an add your other account as signer.

**Comment by piyalbasu** [comment]
Thanks for your feedback! This is actually something we are considering for the future

**Comment by zaibon** [comment]
As a workaround for me a t the moment, ca you tell me what algorithm is used to generate the mnemonic so I can convert my private keys manually ?

**Comment by antb123** [comment]
I had the same issue - not sure I want a new account and then have to move the assets over.

**Comment by piyalbasu** [comment]
Apologies for the late response, I was on holiday last week. Unfortunately, it is actually not possible to generate a mnemonic from a private key, which is a security feature of mnemonic phrases. As a workaround, you could create a Freighter account and transfer funds into it from your other account. Sorry about that!

**Comment by the-solipsist** [comment]
Hi, @antb123. As an alternative, you could create a Freighter account and then merge an existing account with the Freighter account.  That way you don't have to keep the old account around.  But that doesn't provide the simplicity that Freighter aims to provide.

**Comment by piyalbasu** [comment]
As of v1.0.6-beta.0, you can now import an account by Secret Key. It is now available in both Firefox and Chrome
