### ISSUE TITLE
Redesign onboarding and recovery flows

### ISSUE THREAD

**Issue by sdfcharles** [stellar/freighter#1401]
This includes allowing skipping the recovery , using an easier confirmation, allowing pasting, using the same layout for backup and recovery

**Comment by charles-sdf** [comment]
Designs [here](https://www.figma.com/design/C3G0a4Gd6RQyplRBppGDsL/Freighter-(SDS-v3)?node-id=1127-15825&t=TmxweYWKsuzQASL1-1)
