### ISSUE TITLE
[SPIKE] Add "Add Token" API method to freighter-api

### ISSUE THREAD

**Issue by piyalbasu** [stellar/freighter#1467]

**Comment by Dynamitetechdev** [comment]
An API to add tokens from Dapp to wallet would be very helpful on stellar

**Comment by piyalbasu** [comment]
https://docs.google.com/document/d/1d4qZ2nCSauPbStRgfQ73JT5SqvT_-JQ972WWeicG0W4/edit?tab=t.0#heading=h.ifujfbhxkpg0
