### ISSUE TITLE
UX for user who has lost password and wants to create a new account

### ISSUE THREAD

**Issue by piyalbasu** [stellar/freighter#1472]
Steps to repro:

When a user forgets their password, they are stuck on the `Enter password` screen. They have the option to `Import using account seed phrase` if they have another account to import, but they have no options if they want to create a new account from scratch. 

Acceptance criteria:

Give users a path to creating a new account from the `Enter password` screen

**Comment by sdfcharles** [comment]
the quick fix here is to add another link under "Import" like "Create a wallet" that takes the user to that flow <img width="360" alt="00-1 Login" src="https://github.com/user-attachments/assets/2a7924a7-454e-4efa-a143-7f7507d6de58">

once the SDS 3.0 changes are in, the welcome screen should look like this with the "Create a wallet" option as well
<img width="360" alt="Login" src="https://github.com/user-attachments/assets/249bfabc-9ebe-446f-8a86-e01b79d90f4b">

**Comment by CassioMG** [comment]
@piyalbasu is this task about simply adding that button to the UI? Do we already have an "account creation" flow which users should navigate to once tapping on that button? Thanks!

**Comment by CassioMG** [comment]
Implemented here: https://github.com/stellar/freighter/pull/1648
