### ISSUE TITLE
Frighter App extension

### ISSUE THREAD

**Issue by Oaviera** [stellar/freighter#1501]
I can't do any transaction at all. Error code: {"operations":[],"transaction":"tx_too_late"} 

I believe the "tx_too_late" mentioned is not true because I do not go beyond 5ec to for the next clik
![Frieghter App](https://github.com/user-attachments/assets/192049ad-3f15-4f3a-a077-e1bf8be312fc)

**Comment by aristidesstaffieri** [comment]
@Oaviera Are you able to provide info about which asset you are adding here?

When adding an asset, Freighter will add a trustline to your asset as well. The timeout for this transaction is set to 180 seconds so I don't expect you would see this unless yours took longer for some reason.

**Comment by Oaviera** [comment]
Hi

I have been trying to "add" new assets (can be USTN, XLX, META Etc) but this time it does not work at all, error message remain the same, see the screenshot 70. Similar result when I try to send existing assets to other wallets error message see attached screenshots71&72

However, in the beginning, when it was working I sometimes could change timeout for the transaction from 180 to 60 seconds..I am not sure if the system sanctioned me

**Comment by aristidesstaffieri** [comment]
Thanks for the info. Is there any chance your computer's clock is fast? I haven't been able to reproduce this yet but did find an old issue that suggests others have run into this due to clock inconsistencies between the client & server.

https://www.reddit.com/r/Stellar/comments/fe4jmb/stellar_error_tx_too_late/

**Comment by Oaviera** [comment]
Hi, we could be closed to the issue,

The clock could be not faster rather I often set it to different regions according to specifics needs.

For example, I am in Australia now but the clock is set for Singapore time and will likely change it the coming weeks/months

**Comment by aristidesstaffieri** [comment]
@Oaviera You mentioned that you tried changing the timeout, do you mind explaining what steps you took? I've been looking at this from the point of the UI workflow that adds a trustline for users when they add an asset, but I don't believe we expose a user configurable setting for the timeout in this case. Are you running a modified Freighter or are you trying to perform this transaction outside of Freighter?

**Comment by Oaviera** [comment]
Hi, before the transaction is executed, indeed,the last step which includes "time out" and "transactions fee" both can be easily changed , see attached screenshots 75,74.Otherwise, I am not technical to modify the App nor transacting outside the Frighteer App (and hope my vpn does't involves anyway)

—

**Comment by Oaviera** [comment]
Updates: By stetting time on my laptop for "Automatic", the issue has been resolved

Aplogies and thanks to be there
