### ISSUE TITLE
Redesign Friendbot and Unfunded account notifications

### ISSUE THREAD

**Issue by piyalbasu** [stellar/freighter#1540]
This design just shows the "unfunded account" notification, but this design can be applied to the Fund With Friendbot notification

Figma: https://www.figma.com/design/C3G0a4Gd6RQyplRBppGDsL/Freighter-(SDS-v3)?node-id=1127-5083&node-type=instance&m=dev

**Comment by JakeUrban** [comment]
"Add XLM" button will route to the "Receive" page until we have an onramp integration
