### ISSUE TITLE
Unable to find or manually add asset

### ISSUE THREAD

**Issue by JakeUrban** [stellar/freighter#1565]
### What version are you using?

5.23.4

### What did you do?

Search for an asset after selecting "Add Asset". Then entered the issuer public key after selecting "Manually Add".

### What did you expect to see?

The asset

### What did you see instead?

No assets found when searching using the asset name, and nothing after searching via public key.

**Comment by piyalbasu** [comment]
Asset is on Testnet: https://horizon-testnet.stellar.org/accounts/GCV24AUR36RWJAECC7JVUPKYY7CDSGIDUSQDC5G3CAMHJQFMH7ZCA3AJ

**Comment by JakeUrban** [comment]
stellar.expert doesn't provide assets that don't have a specific threshold of activity, so there is nothing to do on Freighter's end.
