### ISSUE TITLE
[DESIGN] Show full xdr and signatures during send/swap flow

### ISSUE THREAD

**Issue by piyalbasu** [stellar/freighter#1570]
Show users the signed xdr that is being sent to the network so users can verify and spot any issues that may have arisen during the signing process

**Comment by JakeUrban** [comment]
Some additional context would be helpful for me here,

- The description makes this sound like a feature request (adding something that doesn't exist today), why is this labeled a bug?
- What is the rationale for making this a P0?

**Comment by sdfcharles** [comment]
Figma: https://www.figma.com/design/C3G0a4Gd6RQyplRBppGDsL/Freighter-(SDS-v3)?node-id=2859-10870&t=RtzfYbDtnpaOhi6K-1

![Image](https://github.com/user-attachments/assets/1db8a851-63c9-4bce-8477-e18bef84c2e7)
