### ISSUE TITLE
QA Freighter v5.25.0-beta.0

### ISSUE THREAD

**Issue by sdfcharles** [stellar/freighter#1622]

**Comment by sdfcharles** [comment]
![Image](https://github.com/user-attachments/assets/768f92df-f2e8-40b2-991d-b85e1ab37ccf)

![Image](https://github.com/user-attachments/assets/138a61d9-7eee-43b9-ba81-6fb3ce261c68)

Account Menu and Network Menu should match the max-width of the container

**Comment by sdfcharles** [comment]
![Image](https://github.com/user-attachments/assets/9698fd52-f254-4fec-b8cb-ea7d9df77f9a)
![Image](https://github.com/user-attachments/assets/5562d9ca-21ba-4f20-8784-adc1ad6a4e89)
![Image](https://github.com/user-attachments/assets/68aee5ba-81a6-438c-aa36-24702a6eb70c)
![Image](https://github.com/user-attachments/assets/9003cf5f-824c-4201-b2cc-4e254ad49c95)
![Image](https://github.com/user-attachments/assets/26895eec-42da-4ab4-a5d3-3d33641773ca)
![Image](https://github.com/user-attachments/assets/7dfdfadb-ded6-4562-bb3d-81ce45818b45)

can we remove the additional padding on these screens?

**Comment by sdfcharles** [comment]
![Image](https://github.com/user-attachments/assets/3bc2e14b-7669-4a92-9cba-9c80252b024e)

- change the Set Max button to secondary styling
- add outline to the swap box

**Comment by sdfcharles** [comment]
![Image](https://github.com/user-attachments/assets/82f7b6ff-c83b-4ad7-8cbd-af31c6f363ab)

can we update this styling to match the Manage Assets screen?

**Comment by aristidesstaffieri** [comment]
Nice thanks @sdfcharles 
@piyalbasu I've started this PR for QA https://github.com/stellar/freighter/pull/1624

**Comment by aristidesstaffieri** [comment]
> ![Image](https://github.com/user-attachments/assets/9698fd52-f254-4fec-b8cb-ea7d9df77f9a) ![Image](https://github.com/user-attachments/assets/5562d9ca-21ba-4f20-8784-adc1ad6a4e89) ![Image](https://github.com/user-attachments/assets/68aee5ba-81a6-438c-aa36-24702a6eb70c) ![Image](https://github.com/user-attachments/assets/9003cf5f-824c-4201-b2cc-4e254ad49c95) ![Image](https://github.com/user-attachments/assets/26895eec-42da-4ab4-a5d3-3d33641773ca) ![Image](https://github.com/user-attachments/assets/7dfdfadb-ded6-4562-bb3d-81ce45818b45)
> 
> can we remove the additional padding on these screens?

Removed this padding in d82958f1e4c0f599c051552e830b9feff08ccc41

**Comment by aristidesstaffieri** [comment]
> ![Image](https://github.com/user-attachments/assets/768f92df-f2e8-40b2-991d-b85e1ab37ccf)
> 
> ![Image](https://github.com/user-attachments/assets/138a61d9-7eee-43b9-ba81-6fb3ce261c68)
> 
> Account Menu and Network Menu should match the max-width of the container

Applied same max width in 0f12c6cd870c4ab579210f9e4d259116c6861908

**Comment by sdfcharles** [comment]
yeah ideally, all the numbers are set to 2 decimals. the URLs can be truncated as well if they are too long.

**Comment by aristidesstaffieri** [comment]
> yeah ideally, all the numbers are set to 2 decimals. the URLs can be truncated as well if they are too long.

I'm not sure if we can truncate after the second decimal without losing valuable info in some cases. Like maybe in some cases where it would be important to be able to see that you have `0.00000099` vs `0.00`.
