### ISSUE TITLE
Feature Request: Allow Freighter to be used on the testnet

### ISSUE THREAD

**Issue by juanhuttemann** [stellar/freighter#171]
### What problem does your feature solve?

Using Freighter in testing environment

### What would you like to see?

A selector for Testnet and Mainnet

### What alternatives are there?

I think there's non

**Comment by piyalbasu** [comment]
Thanks for your feedback! You are correct, there is not a way to switch between Mainnet and Testnet on the official extension you download from the Chrome store. If you really want to test on Testnet, you can clone this repo and build the extension locally using `yarn build:extension`. It will build a version of the extension that runs on Testnet

**Comment by leighmcculloch** [comment]
+1 I think this feature is valuable. I attempted to integrate Freighter into a tool and not being able to test on testnet with the chrome store version is a pretty steep barrier to cross.

**Comment by piyalbasu** [comment]
As of the latest version, `1.1.0`, you are now able to toggle between Testnet and Mainnet
