### ISSUE TITLE
QA Freighter v5.26.0-beta.0

### ISSUE THREAD

**Issue by sdfcharles** [stellar/freighter#1736]
Release + Context: https://stellarfoundation.slack.com/archives/C03347FNAHK/p1734023353188429

**Comment by piyalbasu** [comment]
When a user's session has timed out and they go to do something that requires auth (like adding a trustline or sending a payment) we show them the new login screen with the bottom nav. It looks a little cramped and the `Want to add another account` copy looks absolutely positioned while the rest of the screen moves slightly. How should we address this? Maybe hide the bottom nav?

https://github.com/user-attachments/assets/8601578d-4019-4351-95f3-e35069a47dae

**Comment by sdfcharles** [comment]
> When a user's session has timed out and they go to do something that requires auth (like adding a trustline or sending a payment) we show them the new login screen with the bottom nav. It looks a little cramped and the `Want to add another account` copy looks absolutely positioned while the rest of the screen moves slightly. How should we address this? Maybe hide the bottom nav?
> 
>  Screen.Recording.2024-12-12.at.2.29.55.PM.mov

@piyalbasu oh yeah let's defs hide the bottom nav. the nav shouldn't be on any login/auth screens.

**Comment by sdfcharles** [comment]
- move the 12/24 toggle to the left and the hide/show button to the right
- update styling on hide/show button to tertiary

![Image](https://github.com/user-attachments/assets/d99d5e64-0566-4fe9-b1c4-2bbcdb7939b3)

![Image](https://github.com/user-attachments/assets/0fe9d58f-7c88-4284-9c4d-b2dc552f8c28)

**Comment by sdfcharles** [comment]
![Image](https://github.com/user-attachments/assets/64bd0a04-79e5-4ae7-85fa-2617ab1a470e)

**Comment by sdfcharles** [comment]
- letter spacing on title is too tight, is this SDS or local?
- update styling on secondary text to secondary text color

![Image](https://github.com/user-attachments/assets/e8fe3390-661b-4b5c-8818-24c9557fc678)

**Comment by sdfcharles** [comment]
- update styling on secondary text to secondary text color
- update styling on buttons to tertiary (dark bg)
- apply border to swap box

![Image](https://github.com/user-attachments/assets/13217d54-98e1-4d87-90e7-142ae3c4054f)

**Comment by sdfcharles** [comment]
- update styling on secondary text to secondary text color
- update styling on buttons to tertiary (dark bg)
- update styling on secondary text to secondary text color

![Image](https://github.com/user-attachments/assets/6a201e4a-c0fc-4f8e-bec3-525b6a235b3d)

**Comment by sdfcharles** [comment]
- fix spacing and padding on network input box
- update styling on secondary text to secondary text color

![Image](https://github.com/user-attachments/assets/796e95d9-9ce7-44f9-916c-dddef186179b)

**Comment by sdfcharles** [comment]
- is this local or SDS?

![Image](https://github.com/user-attachments/assets/e51a4cc4-0899-45d3-9b5b-29fa868346f8)

**Comment by sdfcharles** [comment]
is this local or SDS? shouldn't be bold

![Image](https://github.com/user-attachments/assets/f6400854-3462-4d51-9d1d-13e86d4145ae)

**Comment by sdfcharles** [comment]
I know we just implemented this but how do we feel about dropping the 24hr line? Once users login, they don't need to know that and once we have auto-lock, that will be a different time. Also would like to drop to reduce visual clutter here.

![Image](https://github.com/user-attachments/assets/6cd68824-1da2-4e9d-85a2-f64e056926b0)

**Comment by piyalbasu** [comment]
> * is this local or SDS?
> 
> ![Image](https://github.com/user-attachments/assets/e51a4cc4-0899-45d3-9b5b-29fa868346f8)

This will be addressed in #1615

**Comment by piyalbasu** [comment]
> * is this local or SDS? shouldn't be bold
> * buttons here should be semibold, not bold (cc [@piyalbasu](https://github.com/piyalbasu) font issue we chatted about)
> 
> ![Image](https://github.com/user-attachments/assets/f6400854-3462-4d51-9d1d-13e86d4145ae)

Yeah, this is the issue we talked about. This is actually from SDS. Looks like it's applying weight 600, but it's rendering as bold. We'll need to address this in SDS

**Comment by piyalbasu** [comment]
Here are some screenshots from 5.26.0-beta.1

<img width="1429" alt="Image" src="https://github.com/user-attachments/assets/0526e0b3-d823-4557-87fa-b82ddbd8fdb6" />
<img width="359" alt="Image" src="https://github.com/user-attachments/assets/c889853d-cd18-4586-9bce-45214399ab91" />
<img width="364" alt="Image" src="https://github.com/user-attachments/assets/d6f80bf8-989a-46d6-8455-56ad5ebd52b4" />
<img width="364" alt="Image" src="https://github.com/user-attachments/assets/320b3b15-6f3d-446e-bfe2-8750e82949d1" />
<img width="363" alt="Image" src="https://github.com/user-attachments/assets/64ab8f11-d95e-49bf-a57a-b36b9f868e10" />
<img width="363" alt="Image" src="https://github.com/user-attachments/assets/69a45699-8714-4cd9-801a-d8964be6d0ec" />
<img width="1428" alt="Image" src="https://github.com/user-attachments/assets/661feb68-38cb-4326-93bd-e5cd4a97385b" />
