### ISSUE TITLE
Feature Request: Make getPublicKey() return a Signed Message

### ISSUE THREAD

**Issue by agenio** [stellar/freighter#179]
### What problem does your feature solve?
Improve authentication to a third party (web application, ecc) ensuring that a user owns the corresponding secret key

### What would you like to see?
In my opinion could be useful if the getPublicKey() will implements:

Accept:
- an input parameter String (this will be an arbitrary token generated by the requesting application)

Return:
- Public Key (this is already returned)
- Message Signed
- Signature

Almost like albedo (albedo.link) does: 
 - see at [albedo documentation](https://albedo.link/playground?section=public_key)
 - and [link](https://github.com/stellar-expert/albedo/issues/24) to see what albedo signs

This feature will permit also to the requesting application (web application, ecc) to check the authentication data

**Comment by dinhduongha** [comment]
Look like we need function signMessage(msg) and verifyMessage(msg, signature), same as https://github.com/orbitlens/stellar-expert-id do.

**Comment by agenio** [comment]
In my opinion would be better like albedo (albedo.link):
https://albedo.link/playground?section=public_key

The view public key function of Albedo return also the signed message and the signature. In this manner is more simple
even for the user because it requires only one UI interaction.

**Comment by wkta** [comment]
+1
this feature would be useful in my opinion

**Comment by aristidesstaffieri** [comment]
version 5.2.6 adds `signBlob` which signs arbitrary data(base64 encoded) & returns signature.
https://github.com/stellar/freighter/releases/tag/5.2.6
