### ISSUE TITLE
Errors signing transactions containing some operations

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/freighter#220]
### What version are you using?

```
1.0.8-beta.0
```

### What did you do?

Attempt to sign a transaction containing a Begin Sponsoring Future Reserves operation, which is operation number 16.

### What did you expect to see?

Transaction get signed.

### What did you see instead?

```
Error: XDR Read Error: Unknown OperationType member for value 16
    at wrappedSendMessageCallback
```

**Comment by piyalbasu** [comment]
This should be fixed in the current version: `1.1.0` 🎉
