### ISSUE TITLE
Feature Request: Import with S secret key without creating an account

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/freighter#221]
### What problem does your feature solve?

It is not possible to import a Stellar account using an S secret key. For users of many legacy products, like account viewer, or the Stellar launch wallet, the secret key the user has is in the form of an S secret key. Freighter only supports import using a [SEP-5](https://stellar.org/protocol/sep-5) mnemonic secret key, and so Freighter is only usable by folks who have created accounts using more modern wallets.

Also for developers building on testnet, who likely have S secret keys generated by the laboratory.stellar.org, there is no straightforward way to use Freighter, albeit this is also prevented by #171.

### What would you like to see?

Import with S secret key.

### What alternatives are there?

None I believe.

**Comment by piyalbasu** [comment]
@leighmcculloch As of v 1.0.6-beta.0, you should be able to import by secret key. Let me know if you're having an issue with it!
https://github.com/stellar/freighter/issues/140

**Comment by leighmcculloch** [comment]
I don't see a way to import an S secret key on version `1.0.8-beta.0` in Chrome.

This is what I see when I have no data:
<img width="859" alt="Screen Shot 2021-03-16 at 12 59 52 PM" src="https://user-images.githubusercontent.com/351529/111372278-a85ee480-8657-11eb-99a5-edf7aacda1f2.png">

This is what I see when I click to import an existing key:
<img width="1066" alt="Screen Shot 2021-03-16 at 1 00 17 PM" src="https://user-images.githubusercontent.com/351529/111372291-abf26b80-8657-11eb-9624-6f76cb098ff8.png">

**Comment by leighmcculloch** [comment]
I'd like to reopen and repurpose this feature request to import a Stellar secret key from the outset without creating a new account, or importing from a seed. It's difficult to discover this and so accessibility to someone who only has a secret key, and doesn't want to create a new account, is low.

**Comment by phocks** [comment]
Agree, this should be an option without first creating another account, or at the very least notify the user that you can import a secret key after you create a new account, as I had to search for this page to even know it was an option. I was about to go find another wallet.

**Comment by GHesericsu** [comment]
I do not see a way to import a secret key please fix

**Comment by piyalbasu** [comment]
Just want to update this old issue to say that we've had a lot of internal discussion about adding import by secret key at the beginning of the user flow. We are choosing not to implement this. We feel that working with a mnemonic phrase is a more secure industry standard way of dealing with accounts

**Comment by piyalbasu** [comment]
If a user really wants to import using secret key, they can do so after they create a separate mnemonic phrase first

**Comment by leighmcculloch** [comment]
> If a user really wants to import using secret key, they can do so after they create a separate mnemonic phrase first

Is the intent that a user who holds only a S secret key will first convert that S secret key into a mnemonic phrase and then import that?

I don't think there are any tools that exist for converting an S secret key to a mnemonic phrase. Doing so is discouraged by SEP-5 too.
