### ISSUE TITLE
Is there a browser-based client-side version of freighter-api?

### ISSUE THREAD

**Issue by ftppro** [stellar/freighter#257]
Is there a browser-based client-side version of freighter-api, so it can be used without installing on the server?

For example, web3.min_1.36.js can be used as a script tag in an HTML file that is run from the local machine.

**Comment by piyalbasu** [comment]
A browser based solution has been created and will be hosted by a CDN at cdnjs.com.

Currently waiting on someone over at cdnjs to review/merge this PR before I can test/close this ticket: https://github.com/cdnjs/packages/pull/807/files

**Comment by piyalbasu** [comment]
This has been merged and now publicly available at: https://cdnjs.com/libraries/stellar-freighter-api
