### ISSUE TITLE
Freighter assigning random images to assets not verified by TOML

### ISSUE THREAD

**Issue by FredericRezeau** [stellar/freighter#261]
### What version are you using?
1.1.3

### What did you do?

- Setup an account to hold several assets with balance, each asset is verified by TOML with an **image** assigned in CURRENCIES field.
- Import the account (first account) to Freighter via Secret Key import.
- Setup an account to hold one asset with balance, the asset has a home_domain set on the issuer account but is not verified via the TOML at home_domain.
- Import the account (second account) to Freighter via Secret Key import.

### What did you expect to see?

For the asset that is not verified by TOML on the second account, Freighter should not assign an image as TOML information is not available (should be a blue dot in current UI).

### What did you see instead?

Freighter assigns a (possibly) random image from an asset of the first account imported.

**Comment by piyalbasu** [comment]
@FredericRezeau Thanks for reporting this. I've been looking into this issue but thus far have not been able to recreate this. If you feel comfortable doing so, could you please tell me the asset code of the asset that is loading the incorrect icon? Thanks!
