### ISSUE TITLE
Freighter v2.0

### ISSUE THREAD

**Issue by piyalbasu** [stellar/freighter#294]
Q1:
- [x] #329 
- [x] #330
- [x] #333
- [x] #337 
- [x] #339
- [x] #340
- [x] #328
- [x] #322 
- [x] #363 

Q2 and Beyond:
- [ ] #364
- [ ] #327 
- [ ] #312 
- [ ] #318
- [ ] #315
- [x] #305 
- [x] #306
- [x] #307
- [ ] #303
- [ ] #310 
- [ ] #309 
- [ ] #304
- [ ] #311 
- [x] #295 
- [ ] #331 
- [ ] #351

**Comment by tomerweller** [comment]
I don't see claimable balances in this plan. I think we should prioritize these. 

1. Claimable balances were designed to be part of a standard payment flow for sending/receiving non-xlm assets without the appropriate trustlines. This is not an "advanced" feature.
2. the user experience for making and claiming claimable balances is not trivial (especially around spam) and stellar wallet are struggling with it. We have an opportunity to set best practices.
