### ISSUE TITLE
Feature: Send Payments

### ISSUE THREAD

**Issue by piyalbasu** [stellar/freighter#322]
*This feature should be created with the ability to export into a UI library in mind*

- [x] #316 
- [x] #323 
- [ ] #325

**Comment by tomerweller** [comment]
I recommend:
- prioritizing claimable balances, as described [here](https://github.com/stellar/freighter/issues/294#issuecomment-1043381521)
- deprioritizing path payments

**Comment by acharb** [comment]
this is done
