### ISSUE TITLE
Reskin: Onboarding Flow

### ISSUE THREAD

**Issue by piyalbasu** [stellar/freighter#329]
* Apply new designs and new copy to Onboarding flow: Account creation -> confirm backup phrase 
* Remove unused svg's from repo

This is the flow you enter when you have NO wallet info stored in `background` (a brand new user, for ex). 

An easy way to get into this flow is to open the DevTools for `chrome-extension://eiodnmeacfjkeaficifjdjomimneiona/_generated_background_page.html` and go to Application -> Local Storage and clear all the data in here. Nav'ing to anywhere in the app should now bring you int the Onboarding flow.

/views involved:
```
<Welcome>
<MnemonicPhrase>
<FullScreenSuccessMessage>
```

**Comment by acharb** [comment]
looks like AccountCreator.tsx also is in this flow (unless it's included on another ticket I missed). Will do as part of this ticket too

**Comment by acharb** [comment]
closed after https://github.com/stellar/freighter/pull/361
