### ISSUE TITLE
Add client SDK to the chrome extension instead of depending on a client-facing package

### ISSUE THREAD

**Issue by fsodano** [stellar/freighter#370]
### What problem does your feature solve?
Integrating a website with multiple wallets, each of them requiring its own SDK to be installed as a dependency is problematic and a waste of resources.

### What would you like to see?
Other wallets such as xBull inject their SDK in the website using the extension itself. It'd be great if the `window.freighterApi` was injected from the extension itself.

### What alternatives are there?

Keep using the client SDK.

**Comment by piyalbasu** [comment]
The ability to inject scripts into an app will soon be deprecated by Chrome/Firefox for security concerns. I appreciate the sentiment here, but unfortunately in the future, the client SDK will be our only option
