### ISSUE TITLE
Issue Transferring from Google Chrome to Brave Browser with extension.

### ISSUE THREAD

**Issue by mikeg9699** [stellar/freighter#371]
### What version are you using? 

Whichever one is currently available on the Chrome store

### What did you do?

Transferring from using Google Chrome browser to Brave browser, added the Freighter extension from the chrome extensions store and then entered the seed phrase to import my wallet.

### What did you expect to see?

I expected to see all three accounts I have on my Freighter wallet transfer over

### What did you see instead?

Only account 1 transferred over leaving account 2 and 3 inaccessible through the extension on the Brave Freighter extension. So how do you transfer the other accounts so they are visible on the newly added extension on brave?

**Comment by piyalbasu** [comment]
Hi,

If you click `Create a new Stellar address`, it will load the next public key from that seed phrase which should be your "Account 2". Similarly, clicking `Create a new Stellar address` once more will load the 3rd public key associated with your phrase.

Hope that helps!
