### ISSUE TITLE
Support for displaying and signing txs with new CAP-21 preconditions

### ISSUE THREAD

**Issue by piyalbasu** [stellar/freighter#394]
Update stellar-sdk to allow parsing of tx and properly display tx attributes

**Comment by jeffreysmooths** [comment]
[CONTRIBUTING.md](https://github.com/stellar/freighter/files/9205019/CONTRIBUTING.md)
[INSTALL-Windows.md](https://github.com/stellar/freighter/files/9205020/INSTALL-Windows.md)
[INSTALL.md](https://github.com/stellar/freighter/files/9205021/INSTALL.md)
[LICENSE-APACHE.txt](https://github.com/stellar/freighter/files/9205022/LICENSE-APACHE.txt)
[README.md](https://github.com/stellar/freighter/files/9205023/README.md)
[SECURITY.md](https://github.com/stellar/freighter/files/9205024/SECURITY.md)
