### ISSUE TITLE
Few issues with 2.0

### ISSUE THREAD

**Issue by antb123** [stellar/freighter#486]
### What version are you using?
Most recent available in google extensions store
Both Using Chromium and google chrome on ubuntu

Issue 1 - icons for assets don't display
![image](https://user-images.githubusercontent.com/17188302/168130091-62a7309e-6fdb-4ccd-b19f-397442ce1164.png)

Issue 2 when I select pay to another asset I get black screen of death
Different source and destination assets
![image](https://user-images.githubusercontent.com/17188302/168130427-530dd2e3-f874-4b3a-8d11-f7b0a6ac28c3.png)

Issue 3
Link on get lumens doesn't work via help.
![image](https://user-images.githubusercontent.com/17188302/168130633-e573ae54-b3ba-4db0-a8ed-2b477f8adb6b.png)

If the user logs into https://clpx.finance clicks on deposit they can fund their account with any asset that supports deposit funding (BTCLN, CLPX, BRL and some others).

Thanks

**Comment by piyalbasu** [comment]
Updating this issue: these should all be resolved now. Thanks for the feedback!
