### ISSUE TITLE
Mobile Support

### ISSUE THREAD

**Issue by alejomendoza** [stellar/freighter#491]
### What problem does your feature solve?

- Enables us to use Freighter as the default Wallet on [Stellar Quest](https://github.com/stellar/sq-royale-vite) without having to fallback to Albedo. 
- Fixes compatibility issues across mobile and desktop devices for users that signed up with Albedo with their phone but now use Freighter on desktop. 
- Increases mass adoption of Freighter since most users find about Stellar using their phone. 

### What would you like to see?

- Mobile web version we can use like [Albedo](https://albedo.link/)'s. 

### What alternatives are there?

- Only Albedo

CC @jesmarsc @tyvdh

**Comment by JakeUrban** [comment]
We're converting this to a milestone since there is lots of tasks associated with this effort
