### ISSUE TITLE
changing trust to liquidity pool shares not displayed properly 

### ISSUE THREAD

**Issue by tomerweller** [stellar/freighter#492]
![image](https://user-images.githubusercontent.com/815704/168405583-65c56c30-cba8-48b5-af07-7c628ce79885.png)

>

**Comment by aristidesstaffieri** [comment]
![Screenshot 2024-03-29 at 2 53 49 PM](https://github.com/stellar/freighter/assets/6886006/96e19560-3b51-4f4e-ac05-f5e207bb0ed8)

This was fixed when the redesign of transaction signing happened earlier this year.
