### ISSUE TITLE
history tab's sent column displays received payments

### ISSUE THREAD

**Issue by JakeUrban** [stellar/freighter#589]
When I look at my account's transaction history, specifically the sent tab, I see a bunch of inbound payments back from July (I've received payments in august).

Also, I created another Stellar account yesterday, but I don't see that in my "Sent" column even though I sent 5 XLM to fund the account.

<img width="355" alt="Screen Shot 2022-08-02 at 3 55 04 PM" src="https://user-images.githubusercontent.com/10968980/182487177-525afbb3-53d0-402d-a481-f4896a701561.png">

<img width="348" alt="Screen Shot 2022-08-02 at 3 55 26 PM" src="https://user-images.githubusercontent.com/10968980/182487219-64170e8d-3921-4843-8412-c5ad70320c31.png">

**Comment by piyalbasu** [comment]
https://github.com/stellar/freighter/pull/595

Release in 2.4.0
