### ISSUE TITLE
LP shares: replace shares balance with asset balances

### ISSUE THREAD

**Issue by tomerweller** [stellar/freighter#593]
<img width="344" alt="image" src="https://user-images.githubusercontent.com/815704/182926970-4be37a11-8442-4e9f-a9ea-915c56dc9787.png">

The LP shares balance doesn't say much about the value of the balance. Maybe we can change this to something like "35 XLM / 3.5 USDC"?

**Comment by piyalbasu** [comment]
Closing as we're choosing not to support enhancements to this feature
