### ISSUE TITLE
"Block malicious or unsafe addresses and domains" isn't protecting users from sending funds to scam wallet

### ISSUE THREAD

**Issue by badcrack3r** [stellar/freighter#617]
Hello team,

I was taking a look at freighter chrome extension I want to inform you about an issue

I noticed that there is option user can enable to protect himself/herself from sending funds to scam/malicious wallets which is "Block malicious or unsafe addresses and domains"

![1](https://user-images.githubusercontent.com/71478636/187185529-d46e1b4c-27a3-4b55-9693-5100919982cf.jpg)

This scam wallets are being identified using stellar.expert . What I found is that even though it's enabled, it's not protecting users from sending funds to scam wallet.
However, I enabled it and tried to send funds to this scam wallet https://stellar.expert/explorer/public/account/GA272U6UMNKYOBDCLH5CDAPZVDG4WAGJWFY2S2RV2DN6YSSOGYECEVOF

![2](https://user-images.githubusercontent.com/71478636/187185550-12b84a61-282b-45aa-aaed-9108ba091172.jpg)

it was sent successfully without any alert about potential dangerous wallet

### What did you do?

1. set [freighter chrome extension](https://github.com/stellar/freighter)
2. now enable Block malicious or unsafe addresses and domains
3. try to send funds to scam wallets for example:  https://stellar.expert/explorer/public/account/GA272U6UMNKYOBDCLH5CDAPZVDG4WAGJWFY2S2RV2DN6YSSOGYECEVOF
4. see that you will be able to send it normally without any preventions

**Comment by hanseartic** [comment]
@badcrack3r can you try to add a trustline (add asset)  to one of the assets issued by a scam-account (e.g. https://stellar.expert/explorer/public/account/GA6ZAQGLDUEODDUUD3UD6PUFJYABWQA26SG5RK6E6CZ6OMD6AZKK5QNF)? In the past I had issues I could not even add a trustline in order to clean out a claimable-balance (see #519).

**Comment by piyalbasu** [comment]
Apologies for the very late update - we did find this issue as well. We were able to fix it in a subsequent release. Please let us know if you're still experiencing an issue with this!
