### ISSUE TITLE
Allow users to sign contracts

### ISSUE THREAD

**Issue by piyalbasu** [stellar/freighter#633]
* add an “Experimental Mode” toggle in `Preferences` that enables Soroban sdk XDR parsing/signing
* show a warning banner that this is an untested and changing api. 
* Mainnet access is disabled in this mode
* Switching off this toggle switches back to Stellar "classic" and re-enables Mainnet access

**Comment by leighmcculloch** [comment]
Dependent on https://github.com/stellar/rs-soroban-sdk/issues/558

**Comment by leighmcculloch** [comment]
No longer dependent on https://github.com/stellar/rs-soroban-sdk/issues/558
