### ISSUE TITLE
Experimental mode: support standard soroban tokens

### ISSUE THREAD

**Issue by tomerweller** [stellar/freighter#641]
Soroban has a standard token contract and interface. Adding first class support for these tokens in Freighter is critical both to dogfood them and establish best UI practices. 

More specifically: 
- [ ] Allow users to manually opt-in to tokens
- [ ] Display token balances 
- [ ] Facilitate soroban payments
- [ ] Facilitate import from classic and export to classic

**Comment by leighmcculloch** [comment]
Alternatively we could take away the need for most of this by doing https://github.com/stellar/rs-soroban-env/issues/528.

**Comment by piyalbasu** [comment]
This is live as of 2.12.0
