### ISSUE TITLE
UI improvement for assets with a long name

### ISSUE THREAD

**Issue by jeesunikim** [stellar/freighter#642]
### What version are you using?

v2.5.0

### What did you do?

I received an NFT via claimable balances and its UI needs some spacing

### What did you expect to see?

minimum padding

### What did you see instead?

<img width="341" alt="padding-plz" src="https://user-images.githubusercontent.com/3912060/194145585-826061f7-6212-4dd4-b704-1ddf508398fa.png">

**Comment by aristidesstaffieri** [comment]
This is fixed in 4.0.1 https://github.com/stellar/freighter/releases/tag/4.0.1
