### ISSUE TITLE
unable to sign transaction any Stellar transactions with Freighter

### ISSUE THREAD

**Issue by Labetto** [stellar/freighter#666]
On November 2nd 2022, freighter has become unusable to sign any Stellar transactions.
The pop up window indicates:
"FREIGHTER IS SET TO MAIN NET
The transaction you're trying to sign is on Public Global Stellar Network; September 2015.
Signing this transaction is not possible at the moment"

**Comment by Labetto** [comment]
Update:
When I switched freighter to Testnet, I was able to sign a 3rd party transaction on the Mainnet

**Comment by piyalbasu** [comment]
Thank you very much for for raising this issue. I've identified the issue and I've released a hotfix. After going through Chrome store approval, it should be available later tonight or early tomorrow morning. I'll also be putting in tests to make sure this doesn't happen again.

In the mean time, please use the workaround of switching Freighter to Testnet

Apologies for the inconvenience!!

https://github.com/stellar/freighter/releases/tag/2.7.1

**Comment by piyalbasu** [comment]
Update: Both the Chrome and Firefox versions have been updated with the fix and are available for download now: https://chrome.google.com/webstore/detail/freighter/bcacfldlkkdogcmkkibnjlakofdplcbk
https://addons.mozilla.org/en-US/firefox/addon/freighter/
