### ISSUE TITLE
Freighter Injects script Tag Into XML Documents

### ISSUE THREAD

**Issue by cwarden** [stellar/freighter#677]
### What version are you using?

2.7.1

### What did you do?

Opened an [XML document](https://xn.pinkhamster.net/report.xml) containing `<test></test>` in chrome.

### What did you expect to see?

```
<test/>
```

### What did you see instead?

```
<test>
<script>window.freighter = true;</script>
</test>
```

**Comment by piyalbasu** [comment]
@cwarden Sorry for the late reply! We are moving away from this model of injecting a script tag. In the upcoming version 3.0, this will no longer be the case
