### ISSUE TITLE
Connecting to an insecure Soroban-RPC breaks Freighter

### ISSUE THREAD

**Issue by paulbellamy** [stellar/freighter#746]
### What version are you using?

Latest from chrome store as of 2022-03-06

### What did you do?

https://user-images.githubusercontent.com/250199/223190623-425db858-142b-4ac0-8820-af15a851e68c.mov

See video above.
- Set freighter to experimental mode.
- Add an insecure soroban-rpc network.
- Switch to it.
- Inspector says the error is: `Cannot connect to insecure soroban-rpc server`

### What did you expect to see?

Either:
a. It to connect. (It worked previously...)
b. A warning so I can recover freighter without uninstalling/reinstalling.

### What did you see instead?

Freighter fails to connect and gets "stuck" on a black screen.

**Comment by aristidesstaffieri** [comment]
Thanks for reporting this, I've opened a PR fixing it and will aim to include it in our next release.

PR: https://github.com/stellar/freighter/pull/748

**Comment by aristidesstaffieri** [comment]
Fixed in https://github.com/stellar/freighter/releases/tag/2.11.1
