### ISSUE TITLE
Soroban Token Balance decoder seems to be wrong

### ISSUE THREAD

**Issue by silence48** [stellar/freighter#815]
https://github.com/stellar/freighter/blob/466546acbfe642e5c9512829c9b877b2a5b1ac7c/%40shared/api/internal.ts#L877

There is a bug referenced in this discord thread: https://discord.com/channels/897514728459468821/1102899675801075813
that shows that soroban token balances report incorrectly.  
![image](https://user-images.githubusercontent.com/35656692/236067130-8330494e-f90b-4c11-a405-c35a9d1425ec.png)

I believe the issue is here, it tries to decode the balance as an scval accountid which I don't think that's what the balance returns.

Decoding it as an account id should return an i128 which is what it should be, but it seems that somewhere converting that to be the number that is displayed to the user, it gets changed.

**Comment by aristidesstaffieri** [comment]
@silence48 thanks for reporting, we have [an open PR](https://github.com/stellar/freighter/pull/817) to fix this decoder.

**Comment by silence48** [comment]
It seems to work for me now! Good work!
