### ISSUE TITLE
Issue withdrawing funds from wallet

### ISSUE THREAD

**Issue by jay112341** [stellar/freighter#852]
I have an issue with the desktop wallet on both Chrome and Firefox. I go through steps to withdraw but once reaching the confirm send screen the 'Send' button is not responsive/clickable.

**Comment by piyalbasu** [comment]
@jay112341 Thanks so much for bringing this to our attention. I identified a bug in the Send flow and just pushed out a fix for it. Upgrading to version 5.0.4 should fix this. Please let me know if you're still experiencing this issue after upgrading
