### ISSUE TITLE
Experimental Mode - 0 decimal tokens are not properly formatted

### ISSUE THREAD

**Issue by aristidesstaffieri** [stellar/freighter#871]
### What version are you using?
Latest, but this bug exists in all versions.

### What did you do?

Use a 0 decimal token and notice that your formatted display value for that token is incorrect.

### What did you expect to see?
The value amount for 0 decimal tokens should be treated "as is", only supports whole numbers, usually to mimic nft use-cases.

### What did you see instead?
Strange value conversion

**Comment by piyalbasu** [comment]
Fixed in Release/5.1.2
