### ISSUE TITLE
`signTransaction(tx)` incorrectly defaults to pubnet passphrase

### ISSUE THREAD

**Issue by aristidesstaffieri** [stellar/freighter#877]
### What version are you using?
5.1.2

### What did you do?
Reported in Discord - https://discord.com/channels/897514728459468821/1019346446014759013/1123931302681399376

`signTransaction(tx)`

These docs should be updated to use the new function signature of `signTransaction(transactionXdr, options)`
https://docs.freighter.app/docs/playground/signTransaction

Also, if you use the old format and don't pass a network, we incorrectly default he passphrase to pubnet here.
https://github.com/stellar/freighter/blob/master/extension/src/background/messageListener/freighterApiMessageListener.ts#L99

### What did you expect to see?
default to the currently selected network

### What did you see instead?
default to pubnet and fail to sign

**Comment by piyalbasu** [comment]
Closing as this is issue has been resolved
