### ISSUE TITLE
Impossible to sign transaction / Failed  User declined access

### ISSUE THREAD

**Issue by Labetto** [stellar/freighter#886]
### What version are you using?
5.2.0

### What did you do?
Click approve transaction on freighter then get error Failed User declined access

**Comment by GHesericsu** [comment]
same please fix!!!!!

**Comment by Labetto** [comment]
Operating system: Mozilla Firefox

**Comment by aristidesstaffieri** [comment]
@GHesericsu can you provide either the transaction's request xdr or an example of the transaction you are trying to approve? I ran through a few basic cases and didn't hit this so I need to know more about your specific transaction.

**Comment by Labetto** [comment]
Any transactions: swap, send

**Comment by Labetto** [comment]
It happens when I want to sign a transaction with 3rd parties: stellarterm, lumenswap.

**Comment by Labetto** [comment]
![Uploading Screenshot.png…]()

**Comment by Labetto** [comment]
When I use Brave instead of Mozilla it works fine so it must be Firefox specific.

**Comment by esteblock** [comment]
Hello. I am having also issues with 5.2.1

**Comment by piyalbasu** [comment]
@esteblock Is your issue only with the Firefox version, as well?

**Comment by piyalbasu** [comment]
Ah great - thank you both for your feedback. I just released a fix in 5.2.2 that should solve the issue. It appears to be because Firefox suddenly started sending a blocking error when it did not in the past.

**Comment by esteblock** [comment]
Thanks! Will check now

**Comment by esteblock** [comment]
Works well! Thanks!

**Comment by Labetto** [comment]
Thanks

**Comment by GHesericsu** [comment]
Ya Thanks for the quick fix.
