### ISSUE TITLE
Could not approve and sign transactions. Empty approval popup window. 

### ISSUE THREAD

**Issue by GHesericsu** [stellar/freighter#888]
### What version are you using?
5.2.0

### What did you do?
I tried to send a transaction from a dapp.
### What did you expect to see?

I expected Freighter approval modal to pop up and I will sign and send the transaction. 
### What did you see instead?

But it shows an empty popup window....I could not approve my transaction. It just happened after today's update to 5.2.0
![Screen Shot 2023-07-11 at 12 30 27 AM](https://github.com/stellar/freighter/assets/60202455/c89b6f7d-42b2-4540-ad35-e94681174644)

**Comment by aristidesstaffieri** [comment]
@GHesericsu can you provide either the transaction's request xdr or an example of the transaction you are trying to approve? I ran through a few basic cases and didn't hit this so I need to know more about your specific transaction.

**Comment by GHesericsu** [comment]
`AAAAAgAAAACuXkqJ1ox09l9NOvG+4q3iSLTffQpQWlYaUQwg/9zkEAACSqEAC98JAAAACAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAGAAAAAEAAAAAAAAABQAAAA0AAAAgbNBde6+63hgro1ExboCLDX1QxuCkFG8OgZoF1xukp9cAAAAPAAAACmNyZWF0ZV9kYW8AAAAAAA0AAAAEREFPMgAAAA0AAAAEREFPMgAAABMAAAAAAAAAAK5eSonWjHT2X0068b7ireJItN99ClBaVhpRDCD/3OQQAAAAAQAAAADZP1x7sOvEqcj3J8XOvE5BGU04JX4dDZEDVrQ7/FKIEwAAAAh0cmFuc2ZlcgAAAAMAAAATAAAAAAAAAACuXkqJ1ox09l9NOvG+4q3iSLTffQpQWlYaUQwg/9zkEAAAABMAAAABbNBde6+63hgro1ExboCLDX1QxuCkFG8OgZoF1xukp9cAAAAKAAAAAAAAAAAAAAACVAvkAAAAAAAAAAAAAAAAAQAAAAYAAAAGbNBde6+63hgro1ExboCLDX1QxuCkFG8OgZoF1xukp9cAAAAPAAAABk5BVElWRQAAAAAABmzQXXuvut4YK6NRMW6Aiw19UMbgpBRvDoGaBdcbpKfXAAAAFAAAAAbZP1x7sOvEqcj3J8XOvE5BGU04JX4dDZEDVrQ7/FKIEwAAAA8AAAAITUVUQURBVEEAAAAG2T9ce7DrxKnI9yfFzrxOQRlNOCV+HQ2RA1a0O/xSiBMAAAAQAAAAAQAAAAEAAAAPAAAACUFzc2V0SW5mbwAAAAAAAAbZP1x7sOvEqcj3J8XOvE5BGU04JX4dDZEDVrQ7/FKIEwAAABQAAAAHO0epFPhvDbwSoWFnUrqHDtEaR7JDU+D/LRal1jDj2E4AAAADAAAAAAAAAACuXkqJ1ox09l9NOvG+4q3iSLTffQpQWlYaUQwg/9zkEAAAAAZs0F17r7reGCujUTFugIsNfVDG4KQUbw6BmgXXG6Sn1wAAAA0AAAAEREFPMgAAAAbZP1x7sOvEqcj3J8XOvE5BGU04JX4dDZEDVrQ7/FKIEwAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAATAAAAAWzQXXuvut4YK6NRMW6Aiw19UMbgpBRvDoGaBdcbpKfXABjCtAAAH9wAAALUAAAGjAAAAAAAAAFIAAAAAAAAAAA=`

**Comment by GHesericsu** [comment]
On futurenet with experimental mode on.  
![Screen Shot 2023-07-11 at 4 42 10 PM](https://github.com/stellar/freighter/assets/60202455/4c2a30fb-c5ff-48c4-b4e6-7e8612c0c932)

**Comment by GHesericsu** [comment]
I use Brave browser. 

I downgraded to Freighter 5.1.2 and it's working fine.

**Comment by piyalbasu** [comment]
@GHesericsu Thanks so much for reporting this. I've just submitted a fix for this in version [5.2.1](https://github.com/stellar/freighter/releases/tag/5.2.1). It should be approved by the extension stores and be available shortly.
