### ISSUE TITLE
I want to be able to sign a raw data. Not just XDR

### ISSUE THREAD

**Issue by GHesericsu** [stellar/freighter#898]
### What problem does your feature solve?

I want to authenticate user access do certain actions such as a post request to my database. If we allow user to sign a raw data instead of restricting them to only sign XDR then we can use the signed raw data to authenticate access. 

### What would you like to see?

I want a method in Freighter API that allows signing of raw data and not just XDR. A crypto wallet should allow users to sign any data they want to. 

### What alternatives are there?

None. 

Thanks.

**Comment by piyalbasu** [comment]
This is now available in @stellar/freighter-api v1.6.0 using the new `signBlob` API method

https://docs.freighter.app/docs/guide/usingFreighterNode
