### ISSUE TITLE
Freigther shows an empty screen when request to sign a transaction including setTrustLineFlagsOp

### ISSUE THREAD

**Issue by mcaruso85** [stellar/freighter#900]
### What version are you using?
Version 5.2.2 in Chrome Browser.

### What did you do?
Whenever a transaction includes the operation "setTrustLineFlagsOp" freigther will not the transaction, it will show an empty screen and it will not let you reject neither approve.

This is a basic example of an xdr that reproduces the issue, it is a transaction with only one setTrustLineFlagsOp operation:

`const xdr = "AAAAAgAAAAAIU75PWrySYWZ8SwCLAT/BoJOpvlSPbkTSYxZGtNoVVgAAAGQAA60eAAAASQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAJh+cdovCbYxCat8bY2caDEQ0ZlhHcEKZMpMM9epERrBAAAAFQAAAAAIU75PWrySYWZ8SwCLAT/BoJOpvlSPbkTSYxZGtNoVVgAAAAJDSEVFU0UxAAAAAAAAAAAAmH5x2i8JtjEJq3xtjZxoMRDRmWEdwQpkykwz16kRGsEAAAACAAAAAQAAAAAAAAAA"

await signTransaction(xdr, { network: ....., accountToSign: ..... })`

The only thing you can do is to close the window. But the problems is that all the dApps that have transactions with this operation, cannot use Freigther.

### What did you expect to see?
Freigther must show the transaction with all the operations.

### What did you see instead?
An empty screen with no buttons, no text, no nothing.

<img width="361" alt="Screen Shot 2023-07-13 at 11 09 36 PM" src="https://github.com/stellar/freighter/assets/101994/d4151d76-73b3-4f0d-8801-53dcab3280c9">

**Comment by piyalbasu** [comment]
@mcaruso85 Thanks for raising this issue! I just pushed a fix to the extension stores and this bug should be fixed as of version 5.2.4
