### ISSUE TITLE
Unable to sign and send transactions on Brave

### ISSUE THREAD

**Issue by GHesericsu** [stellar/freighter#913]
### What version are you using?
5.2.4

### What did you do?

I submmited a transaction(a custom contract call) via a dapp. 

### What did you expect to see?

I expected to be able to sign and send a transaction

### What did you see instead?

![Screen Shot 2023-07-25 at 5 27 42 PM](https://github.com/stellar/freighter/assets/60202455/708a9967-e46d-4f32-a213-86e17d692db3)

The signing window did pop up but approving it did nothing. It works fine on Chrome, but not on Brave.

**Comment by GHesericsu** [comment]
`AAAAAgAAAACuXkqJ1ox09l9NOvG+4q3iSLTffQpQWlYaUQwg/9zkEAACzHIAAKAsAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAGAAAAAAAAAAFAAAAEgAAAAG3ACjCnTRxWkwYr4XCOlrTr3wlPwltoD4NLP4NF74hfQAAAA8AAAAKY3JlYXRlX2RhbwAAAAAADQAAAAVURUVTVAAAAAAAAA0AAAAFVEVFU1QAAAAAAAASAAAAAAAAAACuXkqJ1ox09l9NOvG+4q3iSLTffQpQWlYaUQwg/9zkEAAAAAEAAAAAAAAAAAAAAAF9wezfkzUZn8mRjb4Mcyzh0RRqqPKcycNgr8anR66U3wAAAAh0cmFuc2ZlcgAAAAMAAAASAAAAAAAAAACuXkqJ1ox09l9NOvG+4q3iSLTffQpQWlYaUQwg/9zkEAAAABIAAAABtwAowp00cVpMGK+Fwjpa0698JT8JbaA+DSz+DRe+IX0AAAAKAAAAAAAAAAAAAAACVAvkAAAAAAAAAAABAAAAAAAAAAQAAAAGAAAAAX3B7N+TNRmfyZGNvgxzLOHRFGqo8pzJw2CvxqdHrpTfAAAAFAAAAAEAAAAAAAAABgAAAAG3ACjCnTRxWkwYr4XCOlrTr3wlPwltoD4NLP4NF74hfQAAAA8AAAAGTkFUSVZFAAAAAAABAAAAAAAAAAYAAAABtwAowp00cVpMGK+Fwjpa0698JT8JbaA+DSz+DRe+IX0AAAAUAAAAAQAAAAAAAAAHX+IIX2CfjN8jMbJ6fdeA28YZRr72AtSYSbUFAGkzMDkAAAAAAAAAAwAAAAAAAAAArl5KidaMdPZfTTrxvuKt4ki0330KUFpWGlEMIP/c5BAAAAAGAAAAAX3B7N+TNRmfyZGNvgxzLOHRFGqo8pzJw2CvxqdHrpTfAAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABtwAowp00cVpMGK+Fwjpa0698JT8JbaA+DSz+DRe+IX0AAAABAAAAAAAAAAYAAAABtwAowp00cVpMGK+Fwjpa0698JT8JbaA+DSz+DRe+IX0AAAANAAAABVRFRVNUAAAAAAAAAQAAAAAAWWTFAAAkUAAAAvAAAAmcAAAAAAAAAeEAAAAA`

**Comment by piyalbasu** [comment]
Hi @GHesericsu I actually can't seem to reproduce this issue. Can you please double check that you have Experimental Mode enabled? Also, there's a chance that the dapp is not passing the above XDR properly to Freighter. I tried signing this XDR using version 5.2.4 on laboratory.stellar.org and I was able to do so successfully

**Comment by GHesericsu** [comment]
Yes I have experimental mode on. I just updated my Brave to the latest and tried to send a transaction, but still got the same error `Bad union switch: 5` However, I have no issues with Chrome.

**Comment by GHesericsu** [comment]
The issue disappeared after I removed an earlier version of Freight from Brave. I had two installed because there was a version that wasn't working. Sorry about the trouble. And thank you!
