### ISSUE TITLE
signTransaction fails when invoked with freighter-wallet api

### ISSUE THREAD

**Issue by alinkon0207** [stellar/freighter#940]
### What version are you using?
I used Soroban client version 1.6.0

### What did you do?
I called signTransaction function in the following function:

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

async function executeTransaction(operation: SorobanClient.xdr.Operation): Promise<number> {
    if (!isConnected() || !isAllowed()) {
        return -1;
    }

    const pubKey = await getPublicKey();
    const sourceAcc = await server.getAccount(pubKey);
    const defFee = '100';

    const transaction0 = new SorobanClient.TransactionBuilder(sourceAcc, {
            fee: defFee, 
            networkPassphrase: SorobanClient.Networks.FUTURENET,
        }).addOperation(operation)
        .setTimeout(30)
        .build();

    const transaction = await server.prepareTransaction(transaction0);
    const txXDR = transaction.toXDR();
    console.log('txXDR:', txXDR);
    const signedTx = await signTransaction(txXDR, {
        network: 'FUTURENET',
        networkPassphrase: SorobanClient.Networks.FUTURENET,
        accountToSign: pubKey,
    });
    const txEnvelope = SorobanClient.xdr.TransactionEnvelope.fromXDR(signedTx, 'base64');
    const tx = new SorobanClient.Transaction(txEnvelope, SorobanClient.Networks.FUTURENET);

    // ...

    return 0;
}

I called the above function with the following code:
const feePubKey = new SorobanClient.Address(feeWallet).toScAddress();
                const res = await executeTransaction(
                    contract.call("set_fee", 
                        SorobanClient.xdr.ScVal.scvU32(fee * 100),
                        SorobanClient.xdr.ScVal.scvAddress(feePubKey),
                ));
                console.log('result:', res);

### What did you expect to see?
I expected success

### What did you see instead?
But I got the following error:
Unable to send message to extension

**Comment by aristidesstaffieri** [comment]
@alinkon0207 are you able to share the contract ID or source code for the contract in question here. I just did a "mint" operation using https://scaffold-soroban.stellar.org/ and was able to sign/submit a transaction through the API. 

[The `Unable to send message to extension` error](https://github.com/stellar/freighter/blob/master/extension/src/contentScript/helpers/redirectMessagesToBackground.ts#L20) means that the browser window that the app runs in was not able to send a message back to the wallet. This can happen for a variety of reasons that can be transient. We can definitely surface more information on this error state so I'll add a ticket to improve the error but in the mean time you can check the background script logs to see what happened in your case.

**Comment by piyalbasu** [comment]
Closing as we didn't receive enough info to look into this more closely
