### ISSUE TITLE
How can a user disconnect wallet from a page?

### ISSUE THREAD

**Issue by nalnir** [stellar/freighter#943]
There is no specific function for that. Local storage has certain values set, but even after deleting those when I reload and check `isConnected()` it will return true and the value will be injected into the storage again. 

One other function is `setAllowed()` but that only sets true.

**Comment by piyalbasu** [comment]
This can be done by going to Settings > Security > Manage connected apps and then clicking Remove next to the domain you'd like to disconnect from:

<img width="359" alt="Screenshot 2024-01-25 at 7 13 52 PM" src="https://github.com/stellar/freighter/assets/6789586/2c21be15-16d4-46bd-9d74-25f482b8b33d">
