### ISSUE TITLE
Chrome Extension Uncaught TypeError

### ISSUE THREAD

**Issue by hasToDev** [stellar/freighter#964]
Get errors when using `Freighter extension 5.5.0` with `Stellar Freighter Api 1.6.0` in Experimental mode.

![f-1](https://github.com/stellar/freighter/assets/44645201/3d47ac48-802d-4f00-8488-f3442b783cad)
![f-2](https://github.com/stellar/freighter/assets/44645201/91eca0ac-02f5-4403-ad0a-cb70fcc97327)

Is there a plan for the newer version of Stellar Freighter Api?

**Comment by mint-pz** [comment]
same here

**Comment by piyalbasu** [comment]
Hi, thanks for raising this. This may be a bug with how we're parsing specific transactions. Would either of you mind sharing an XDR you're trying to sign so I can test? @hasToDev @mint-pz

**Comment by piyalbasu** [comment]
@hasToDev Thanks for sharing. We've found the bug and are working on the solution right now. We should have an updated release shortly that fixes the issue. Thanks for your patience!

**Comment by piyalbasu** [comment]
This has been fixed in version 5.5.1: https://github.com/stellar/freighter/releases/tag/5.5.1

**Comment by piyalbasu** [comment]
Correction: This has been fixed in version 5.5.2

**Comment by mint-pz** [comment]
Thank you @piyalbasu
