### ISSUE TITLE
Unable to send message to extension 

### ISSUE THREAD

**Issue by GHesericsu** [stellar/freighter#983]
### What version are you using?

5.6.1

### What did you do?

I submitted a transaction on futurenet that needs to be signed. I'm using soroban-client@1.0.0-beta.2

The repo is here: https://github.com/deep-ink-ventures/multiclique-frontend/blob/1c4057fbbd545a3599ef2ac57a796267428e5825/src/pages/account/create.tsx#L35

the XDR: 
`AAAAAgAAAACsJpXRB7ACDdoFax6wRWJBsexMmxfw+m7WQBQSLI/r5wAAZm0AAKiXAAAAAQAAAAEAAAAAAAAAAAAAAABlFMmRAAAAAAAAAAEAAAAAAAAAGAAAAAEAAAAAAAAAAAAAAACsJpXRB7ACDdoFax6wRWJBsexMmxfw+m7WQBQSLI/r559DSMedH5LxGqUhtLToEc+AB4n17ceHuRCceSu6UdZWAAAAAIdlpG8+QDCCj/5C7AsTEIRRa2wKvEsC/5OPWOdzqwI5AAAAAQAAAAAAAAABAAAAAAAAAAAAAAAArCaV0QewAg3aBWsesEViQbHsTJsX8Ppu1kAUEiyP6+efQ0jHnR+S8RqlIbS06BHPgAeJ9e3Hh7kQnHkrulHWVgAAAACHZaRvPkAwgo/+QuwLExCEUWtsCrxLAv+Tj1jnc6sCOQAAAAAAAAABAAAAAAAAAAEAAAAHh2Wkbz5AMIKP/kLsCxMQhFFrbAq8SwL/k49Y53OrAjkAAAABAAAABgAAAAEvKT2Sb2tlMi+v74YEsV8U+0oMSue50PHe0pRJzJlBGgAAABQAAAABAAHKFwAAKBgAAABoAAAAAAAADcAAAAAA`

### What did you expect to see?

I expect to see a popup to approve the transaction

### What did you see instead?

No popup. And I see this error message in the dev console: 

`Unable to send message to extension`

`Error: XDR Read Error: unknown PublicKeyType member for value -2065429947
    at h (contentScript.min.js:1:8782)`

**Comment by aristidesstaffieri** [comment]
@GHesericsu there were xdr changes introduced in preview 11, so the xdr error might suggest that the contract needs to be compiled for the newest protocol version. Do you know if the contract was built using a preview 11 compatible cli version?

**Comment by GHesericsu** [comment]
Issue resolved. We need to turn on experimental mode. I reinstalled Freighter and did not turn it back on. Sorry about the trouble.
