### ISSUE TITLE
Soroban-RPC URL does not get saved

### ISSUE THREAD

**Issue by esteblock** [stellar/freighter#990]
### What version are you using?
Freighter 5.6.1 and 5.6.2
### What did you do?
Configured a new network.
- Set Horizon RPC
- Set Soroban RPC
Type: "Save"

Then, come back to that network settings

### What did you expect to see?
I expect to see both RPC URL's that I saved before

### What did you see instead?
I only see the Horizon RPC URL.  "Soroban RPC" field is empty

**Comment by aristidesstaffieri** [comment]
@esteblock thanks for reporting this bug!
I've drafted a PR that should resolve it, basically there was a mismatch in response types from when the split of the rpc urls originally happened, which caused the soroban rpc URLs to fall through and not be added to responses.

https://github.com/stellar/freighter/pull/992

I'm working on getting this reviewed now and then will prioritize a release right after that.
Please reach out if you have any remaining concerns about the proposed change to fix this, thanks.

**Comment by esteblock** [comment]
Great. #992 solved #991 
However this issue "Soroban-RPC URL does not get saved" is not totally solved with #992 (version 5.6.3

I do:

![Screenshot from 2023-10-11 00-32-42](https://github.com/stellar/freighter/assets/2274485/ef1265a8-621a-4252-b299-50b0bf18c5cd)

![Screenshot from 2023-10-11 00-03-03](https://github.com/stellar/freighter/assets/2274485/660c5526-6002-45bb-8e7a-6e70a680b219)


I enter a Soroban RPC URL:

![Screenshot from 2023-10-11 00-36-53](https://github.com/stellar/freighter/assets/2274485/64d47628-b181-4b04-9911-6926f962e713)


I type save.... and then... when I open settings again it is gone!

![Screenshot from 2023-10-11 00-33-16](https://github.com/stellar/freighter/assets/2274485/9d8988d5-89db-4919-9949-72b4966fc27a)


However, from my broswser, using @stellar/freighter-api version 1.7.1 I can see that the new sorobanRpcUrl it has been saved!

```
Object { network: "CUSTOM", networkUrl: "http://localhost:8000/soroban/rpc", networkPassphrase: "Test SDF Future Network ; October 2022", sorobanRpcUrl: "http://soroban.url/" }
```

So it's just something about the extension frontend that needs to be fixed in order to avoid confusion :)

**Comment by aristidesstaffieri** [comment]
ah yeah @esteblock so I actually didn't realize there was a display bug when I worked on #992 so give me a bit to patch that one and we will cut another patch release to fix that as well.

**Comment by aristidesstaffieri** [comment]
alright @esteblock thanks again for pointing that out. This was the cause of the display bug for custom networks.
https://github.com/stellar/freighter/pull/999

I'll get this into another patch release asap.

**Comment by esteblock** [comment]
Great!

**Comment by aristidesstaffieri** [comment]
@esteblock 5.6.4 has been published and includes the fix for the display side as well.
https://github.com/stellar/freighter/releases/tag/5.6.4

**Comment by esteblock** [comment]
@aristidesstaffieri Thanks! I just experimented and I confirm that in 5.6.4 this has been solved!
